import { Header } from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <div className="relative h-[200vh]">
      <Head>
        <title>Movie | website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main></main>
    </div>
  );
}
