import { Header, Hero, Modal, Row, Subscription } from "@/components";
import { IMovie, Mylist, Product } from "@/interfaces/app.interface";
import { API_REQUEST } from "@/service/api.service";
import { GetServerSideProps } from "next";
import Head from "next/head";
import { useInfoStore } from "@/store";
import { getList } from "@/helpers/lists";

export default function Home({
  trending,
  topRated,
  tvTopRated,
  popular,
  documentary,
  comedy,
  family,
  war,
  history,
  products,
  subscription,
  list

}: HomeProps): JSX.Element {
  const { modal } = useInfoStore();


  if (!subscription.length) return <Subscription products={products} />

  return (
    <div className="relative min-h-screen bg-gradient-to-b from-gray-900/20 ">
      <Head>
        <title>Movie | website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main className="relative pl-4 pb-24 lg:space-y-24 lg:pl-16">
        <Hero trending={trending} />
        <section>
          <Row title="Top Rated" movies={topRated} />
          <Row title="TV Show" movies={tvTopRated} isBig={true} />
          {list.length ? <Row title="MY List" movies={list.map(c => c)} /> : null}
          <Row title="Documentary" movies={documentary} />
          <Row title="Popular" movies={popular} isBig={true} />
          <Row title="Comedy" movies={comedy} />
          <Row title="Family" movies={family} isBig={true} />
          <Row title="War" movies={war} />
          <Row title="History" movies={history} />
        </section>
      </main>
      {modal && <Modal />}
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async ({ req }) => {
  const user_id = req.cookies.user_id

  if (!user_id) {
    return {
      redirect: { destination: '/auth', permanent: false }
    }
  }

  const [
    trending,
    topRated,
    tvTopRated,
    popular,
    documentary,
    comedy,
    family,
    war,
    history,
    products,
    subscription
  ] = await Promise.all([
    fetch(API_REQUEST.trending).then((res) => res.json()),
    fetch(API_REQUEST.top_rated).then((res) => res.json()),
    fetch(API_REQUEST.tv_top_rated).then((res) => res.json()),
    fetch(API_REQUEST.popular).then((res) => res.json()),
    fetch(API_REQUEST.documentary).then((res) => res.json()),
    fetch(API_REQUEST.comedy).then((res) => res.json()),
    fetch(API_REQUEST.family).then((res) => res.json()),
    fetch(API_REQUEST.war).then((res) => res.json()),
    fetch(API_REQUEST.history).then((res) => res.json()),
    fetch(API_REQUEST.products_list).then((res) => res.json()),
    fetch(`${API_REQUEST.subscription}/${user_id}`).then((res) => res.json()),
  ]);

  const myList: Mylist[] = await getList(user_id)
  console.log(user_id)

  return {
    props: {
      trending: trending.results,
      topRated: topRated.results,
      tvTopRated: tvTopRated.results,
      popular: popular.results,
      documentary: documentary.results.reverse(),
      comedy: comedy.results,
      family: family.results,
      war: war.results,
      history: history.results,
      products: products.products.data,
      subscription: subscription.subscription.data,
      list: myList.map(c => c.product),
    },
  };
};

interface HomeProps {
  trending: IMovie[];
  topRated: IMovie[];
  tvTopRated: IMovie[];
  popular: IMovie[];
  documentary: IMovie[];
  comedy: IMovie[];
  family: IMovie[];
  war: IMovie[];
  history: IMovie[];
  products: Product[];
  subscription: string[]
  list: IMovie[]
}
